# Generated by Django 6.0.6 on 2026-06-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('edupilot_core', '0002_student_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('fee', 'Fee'), ('salary', 'Salary'), ('other', 'Other')], default='other', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='edupilot_user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='edupilot_user_permissions_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
