# Generated by Django 6.0.6 on 2026-06-19 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edupilot_core', '0004_scholarship_transportroute'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='edupilot_core.feeplan')),
                ('scholarship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='edupilot_core.scholarship')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_assignment', to='edupilot_core.student')),
                ('transport_route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='edupilot_core.transportroute')),
            ],
        ),
    ]
