# Generated by Django 6.0.6 on 2026-06-20 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edupilot_core', '0006_alter_feehead_options_remove_student_class_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeGenerationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_enabled', models.BooleanField(default=False)),
                ('generation_day', models.PositiveIntegerField(default=1)),
                ('generation_time', models.TimeField(default='09:00:00')),
                ('send_notifications', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email')], max_length=10)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edupilot_core.student')),
            ],
        ),
    ]
