# Generated by Django 6.0.6 on 2026-06-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edupilot_core', '0009_automationjob_automationjobdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('parent', 'Parent'), ('teacher', 'Teacher')], default='student', max_length=10),
        ),
    ]
