# Generated by Django 6.0.6 on 2026-06-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edupilot_core', '0011_salarystructure_salaryvoucher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='employee_id',
            new_name='employment_type',
        ),
        migrations.RemoveField(
            model_name='salarystructure',
            name='allowances',
        ),
        migrations.RemoveField(
            model_name='salarystructure',
            name='basic_salary',
        ),
        migrations.AddField(
            model_name='teacher',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default='', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='cnic',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='designation',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='house_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='joining_date',
            field=models.DateField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='medical_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='overtime',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='special_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='transport_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='utility_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
