# Generated by Django 6.0.6 on 2026-06-23 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edupilot_core', '0013_alter_teacher_address_alter_teacher_basic_salary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryAutomationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('success_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryAutomationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_enabled', models.BooleanField(default=False)),
                ('generation_day', models.PositiveIntegerField(default=30)),
                ('generation_time', models.TimeField(default='18:00:00')),
                ('send_notifications', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryAutomationJobDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='edupilot_core.salaryautomationjob')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edupilot_core.teacher')),
            ],
        ),
    ]
