# Generated by Django 6.0.6 on 2026-06-25 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edupilot_core', '0014_salaryautomationjob_salaryautomationsettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feevoucher',
            name='year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterUniqueTogether(
            name='feevoucher',
            unique_together={('student', 'month', 'year')},
        ),
    ]
